#ifndef BLACKCAT_KEYCHAIN_CIPHER_AES_H
#define BLACKCAT_KEYCHAIN_CIPHER_AES_H 1

#include <basedefs/defs.h>

DECL_BLACKCAT_CIPHER_PROCESSOR(aes128, ktask, p_layer)

DECL_BLACKCAT_CIPHER_PROCESSOR(aes192, ktask, p_layer)

DECL_BLACKCAT_CIPHER_PROCESSOR(aes256, ktask, p_layer)

#endif
